
sudo: false
dist: trusty
language: java

addons:
  apt:
    packages:
      - openjdk-6-jdk

jdk:
  - openjdk6

script:
  ./gradlew clean build jacocoTestReport --info

after_success:
  - bash <(curl -s https://codecov.io/bash)
